//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerPlusClient.ServiceReferenceWeather {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWeather.IWeatherServices")]
    public interface IWeatherServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherServices/GetCurrentConditions", ReplyAction="http://tempuri.org/IWeatherServices/GetCurrentConditionsResponse")]
        FarmerPlusDataObjectLayer.Conditions GetCurrentConditions(string inputrequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServicesChannel : FarmerPlusClient.ServiceReferenceWeather.IWeatherServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServicesClient : System.ServiceModel.ClientBase<FarmerPlusClient.ServiceReferenceWeather.IWeatherServices>, FarmerPlusClient.ServiceReferenceWeather.IWeatherServices {
        
        public WeatherServicesClient() {
        }
        
        public WeatherServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FarmerPlusDataObjectLayer.Conditions GetCurrentConditions(string inputrequest) {
            return base.Channel.GetCurrentConditions(inputrequest);
        }
    }
}
