//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerPlusScheduarManager.ServiceReferenceCommon {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCommon.ICommonHelperService")]
    public interface ICommonHelperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/DoWork", ReplyAction="http://tempuri.org/ICommonHelperService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/InsertAndGetSemantics", ReplyAction="http://tempuri.org/ICommonHelperService/InsertAndGetSemanticsResponse")]
        int InsertAndGetSemantics(string file_path, string urdu_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetLookupGroupId", ReplyAction="http://tempuri.org/ICommonHelperService/GetLookupGroupIdResponse")]
        int GetLookupGroupId(string lookup_group_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/InsertInLookup", ReplyAction="http://tempuri.org/ICommonHelperService/InsertInLookupResponse")]
        int InsertInLookup(string item_name, int group_id, int semantics_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/InsertCompany", ReplyAction="http://tempuri.org/ICommonHelperService/InsertCompanyResponse")]
        int InsertCompany(string compay_name, string contact_number, int semantics_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetLookupList", ReplyAction="http://tempuri.org/ICommonHelperService/GetLookupListResponse")]
        System.Data.DataSet GetLookupList(string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetCompaniesList", ReplyAction="http://tempuri.org/ICommonHelperService/GetCompaniesListResponse")]
        System.Data.DataSet GetCompaniesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetCitiesList", ReplyAction="http://tempuri.org/ICommonHelperService/GetCitiesListResponse")]
        System.Data.DataSet GetCitiesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/InsertInAgriEquipmentMapping", ReplyAction="http://tempuri.org/ICommonHelperService/InsertInAgriEquipmentMappingResponse")]
        int InsertInAgriEquipmentMapping(int agriequiplkpid, int city_id, int company_id, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetDistrictsList", ReplyAction="http://tempuri.org/ICommonHelperService/GetDistrictsListResponse")]
        System.Data.DataSet GetDistrictsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/InsertInCities", ReplyAction="http://tempuri.org/ICommonHelperService/InsertInCitiesResponse")]
        int InsertInCities(string city_name, int district_id, int semantics_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/InsertInDistricts", ReplyAction="http://tempuri.org/ICommonHelperService/InsertInDistrictsResponse")]
        int InsertInDistricts(string district_name, int semantics_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetComplaints", ReplyAction="http://tempuri.org/ICommonHelperService/GetComplaintsResponse")]
        System.Data.DataSet GetComplaints(int service_id, int category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetComplaintFollowup", ReplyAction="http://tempuri.org/ICommonHelperService/GetComplaintFollowupResponse")]
        string GetComplaintFollowup(int complaint_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/UpdateComplaintFolloup", ReplyAction="http://tempuri.org/ICommonHelperService/UpdateComplaintFolloupResponse")]
        int UpdateComplaintFolloup(int complaint_id, string complaint_followup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetVendorCodes", ReplyAction="http://tempuri.org/ICommonHelperService/GetVendorCodesResponse")]
        System.Data.DataSet GetVendorCodes(int is_mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/CreateVendorCode", ReplyAction="http://tempuri.org/ICommonHelperService/CreateVendorCodeResponse")]
        int CreateVendorCode(string vendor_code, int is_mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetPhoneRanges", ReplyAction="http://tempuri.org/ICommonHelperService/GetPhoneRangesResponse")]
        System.Data.DataSet GetPhoneRanges(int is_mobile, int vendor_code_id, int city_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetLoginInfor", ReplyAction="http://tempuri.org/ICommonHelperService/GetLoginInforResponse")]
        System.Data.DataSet GetLoginInfor(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetCitiesInADistrict", ReplyAction="http://tempuri.org/ICommonHelperService/GetCitiesInADistrictResponse")]
        System.Data.DataSet GetCitiesInADistrict(int district_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetCallerOfACity", ReplyAction="http://tempuri.org/ICommonHelperService/GetCallerOfACityResponse")]
        System.Data.DataSet GetCallerOfACity(int city_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetCallerOfADistrict", ReplyAction="http://tempuri.org/ICommonHelperService/GetCallerOfADistrictResponse")]
        System.Data.DataSet GetCallerOfADistrict(int district_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonHelperService/GetUrduNameOfALookupId", ReplyAction="http://tempuri.org/ICommonHelperService/GetUrduNameOfALookupIdResponse")]
        string GetUrduNameOfALookupId(int lkp_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonHelperServiceChannel : FarmerPlusScheduarManager.ServiceReferenceCommon.ICommonHelperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonHelperServiceClient : System.ServiceModel.ClientBase<FarmerPlusScheduarManager.ServiceReferenceCommon.ICommonHelperService>, FarmerPlusScheduarManager.ServiceReferenceCommon.ICommonHelperService {
        
        public CommonHelperServiceClient() {
        }
        
        public CommonHelperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonHelperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonHelperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonHelperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public int InsertAndGetSemantics(string file_path, string urdu_name) {
            return base.Channel.InsertAndGetSemantics(file_path, urdu_name);
        }
        
        public int GetLookupGroupId(string lookup_group_name) {
            return base.Channel.GetLookupGroupId(lookup_group_name);
        }
        
        public int InsertInLookup(string item_name, int group_id, int semantics_id) {
            return base.Channel.InsertInLookup(item_name, group_id, semantics_id);
        }
        
        public int InsertCompany(string compay_name, string contact_number, int semantics_id) {
            return base.Channel.InsertCompany(compay_name, contact_number, semantics_id);
        }
        
        public System.Data.DataSet GetLookupList(string groupName) {
            return base.Channel.GetLookupList(groupName);
        }
        
        public System.Data.DataSet GetCompaniesList() {
            return base.Channel.GetCompaniesList();
        }
        
        public System.Data.DataSet GetCitiesList() {
            return base.Channel.GetCitiesList();
        }
        
        public int InsertInAgriEquipmentMapping(int agriequiplkpid, int city_id, int company_id, int price) {
            return base.Channel.InsertInAgriEquipmentMapping(agriequiplkpid, city_id, company_id, price);
        }
        
        public System.Data.DataSet GetDistrictsList() {
            return base.Channel.GetDistrictsList();
        }
        
        public int InsertInCities(string city_name, int district_id, int semantics_id) {
            return base.Channel.InsertInCities(city_name, district_id, semantics_id);
        }
        
        public int InsertInDistricts(string district_name, int semantics_id) {
            return base.Channel.InsertInDistricts(district_name, semantics_id);
        }
        
        public System.Data.DataSet GetComplaints(int service_id, int category_id) {
            return base.Channel.GetComplaints(service_id, category_id);
        }
        
        public string GetComplaintFollowup(int complaint_id) {
            return base.Channel.GetComplaintFollowup(complaint_id);
        }
        
        public int UpdateComplaintFolloup(int complaint_id, string complaint_followup) {
            return base.Channel.UpdateComplaintFolloup(complaint_id, complaint_followup);
        }
        
        public System.Data.DataSet GetVendorCodes(int is_mobile) {
            return base.Channel.GetVendorCodes(is_mobile);
        }
        
        public int CreateVendorCode(string vendor_code, int is_mobile) {
            return base.Channel.CreateVendorCode(vendor_code, is_mobile);
        }
        
        public System.Data.DataSet GetPhoneRanges(int is_mobile, int vendor_code_id, int city_id) {
            return base.Channel.GetPhoneRanges(is_mobile, vendor_code_id, city_id);
        }
        
        public System.Data.DataSet GetLoginInfor(string username, string password) {
            return base.Channel.GetLoginInfor(username, password);
        }
        
        public System.Data.DataSet GetCitiesInADistrict(int district_id) {
            return base.Channel.GetCitiesInADistrict(district_id);
        }
        
        public System.Data.DataSet GetCallerOfACity(int city_id) {
            return base.Channel.GetCallerOfACity(city_id);
        }
        
        public System.Data.DataSet GetCallerOfADistrict(int district_id) {
            return base.Channel.GetCallerOfADistrict(district_id);
        }
        
        public string GetUrduNameOfALookupId(int lkp_id) {
            return base.Channel.GetUrduNameOfALookupId(lkp_id);
        }
    }
}
